version: '3'
services:
  database: 
    image: 'mongo'
    container_name: 'movies-app-container'
    environment:
      - MONGO_INITDB_DATABASE = movies
      - MONGO_INITDB_ROOT_USERNAME = root
      - MONGO_INITDB_ROOT_PASSWORD = test
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./movies.json:/docker-entrypoint-initdb.d/movies.json:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'